// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZIUL7SWnHGcfgO_cwq5TVr9cE23sdnlA',
    appId: '1:956849813475:web:029e30a07dd6fec7a412d6',
    messagingSenderId: '956849813475',
    projectId: 'driver-ae714',
    authDomain: 'driver-ae714.firebaseapp.com',
    databaseURL: 'https://driver-ae714-default-rtdb.firebaseio.com',
    storageBucket: 'driver-ae714.appspot.com',
    measurementId: 'G-B3H2H4EJN9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSWSot_76y16lU4o4uumR8HX0lVQbAP5c',
    appId: '1:956849813475:android:0ad07d0852cb6171a412d6',
    messagingSenderId: '956849813475',
    projectId: 'driver-ae714',
    databaseURL: 'https://driver-ae714-default-rtdb.firebaseio.com',
    storageBucket: 'driver-ae714.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCl1QojzpHC4HvTEnD3U3ZC9NNICwemWe8',
    appId: '1:956849813475:ios:e82ed5e21d860e75a412d6',
    messagingSenderId: '956849813475',
    projectId: 'driver-ae714',
    databaseURL: 'https://driver-ae714-default-rtdb.firebaseio.com',
    storageBucket: 'driver-ae714.appspot.com',
    iosBundleId: 'com.digigrow.driver.ios',
  );
}
